# Generated by Django 2.2.4 on 2019-09-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
