# Generated by Django 2.2.4 on 2019-09-12 06:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedbacks', '0002_auto_20190911_1234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('article', 'user')},
        ),
    ]
